name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npm list --depth=0
        
    - name: Check for test files
      run: |
        echo "Checking for test files..."
        find src -name "*.test.js" -o -name "*.spec.js"
        
    - name: Run tests
      run: |
        echo "Running tests..."
        CI=true npm test -- --verbose
        
    - name: Build project
      run: |
        echo "Building project..."
        CI=true npm run build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          coverage/
          test-results/ 